# Generated by Django 5.0.3 on 2024-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0002_contactform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
